### PR TITLE
0.1.0 commit

### PR DESCRIPTION
**Pull request by iron-rain**
### Description
OpenSearch Helm chart variant, this chart is a redux of an OpenDistro chart I wrote for work, if there is interest in this type of deployment I will keep working on it as an opensource project! 

The chart is still very much an alpha release, the core concept of node based objects functions though. 

This chart treats OpenSearch nodes as objects, administrators are able to define the node type (warm, cold, ingest, master etc) and pod parameters, the configuration is then deployed as a scalable Statefulset.

There is no Dashboards included in this chart, that will be a separate component.

Please see the Helm [README](https://github.com/iron-rain/opensearch-devops/blob/main/Helm/README.md) for a the current and future features I have planned. 
 
### Issues Resolved
- 2
- 5
- Scalability and granularity in cluster definition, this is not an OpenSearch specific issue, we found with the OpenDistro or Elasticsearch charts that they are mainly geared towards the Master, Data, Client set up, this chart allows multiple variants of each type to be deployed. 
 
### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
Hi @iron-rain thanks for the work 1st of all, we absolutely welcome these contributions to OpenSearch.
Have you check this helm chart PR https://github.com/opensearch-project/opensearch-devops/pull/4?
Is there anything that is different from yours compares to @theAlgo?

Thanks.

**Comment by TheAlgo** [comment]
In my opinion this chart follows a pattern, it will great if we can have something generic which can be moulded into various deployment strategies.

**Comment by iron-rain** [comment]
@peterzhuamazon The main difference is the nodes as objects concept, so you could deploy your entire Opensearch system as a single Helm chart and update/edit node pools separately. 

@TheAlgo I'm going to keep working away at it, if you need any help or want bits for your chart happy to help integrate!

**Comment by peterzhuamazon** [comment]
Hi @iron-rain we have merged the 1st part of generic Helm rewrite for OpenSearch #4 
Do you think we can close this PR and start adding improvement on top of #4?

Thanks.

**Comment by peterzhuamazon** [comment]
Hi @iron-rain it has been 7 days since we have the last conversation.
Due to #4 being merged and #10 on the way, we will close this PR and hope you can help improve based on the new Helm.

Thanks.

**Pull request closed without merging**
