### PR TITLE
Remove Helm folder and add a submodule for Helm Charts

### LINKED ISSUE #66: [Migration][Helm] Cleanup the helm folders in devops repo and add pointers to helm-charts repo
**Is your feature request related to a problem? Please describe.**
Cleanup the helm folders in devops repo and add pointers to helm-charts repo
https://github.com/opensearch-project/helm-charts

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by TheAlgo**
### Description
Remove stale folders of Helm Charts from the repo and add pointers to the new helm repo
 
### Issues Resolved
#66 
 
### Check List
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by TheAlgo** [comment]
@peterzhuamazon @DandyDeveloper @smlx Have a look a this cleaning when free. Thanks

**Review by DandyDeveloper — APPROVED** [review]
No issues, but why out of interest?

**Comment by peterzhuamazon** [comment]
> No issues, but why out of interest?
> 
> Perhaps update the README as well since we have the chance?

Yes @TheAlgo probably we can just add a simple README within the helm-charts folder and explain why we deprecated this part and more to helm-charts repo?

Thanks.

**Comment by TheAlgo** [comment]
@peterzhuamazon @DandyDeveloper I agree but wanted to understand why we want to keep the helm folder lying here and create confusions. People may land to this repo and install the stale chart and create issues onto that. IMO deprecation is not a good word to describe the initial chart since it was WIP. We just moved our code. 

But yeah if everyone else agrees on not removing the folder I can change the behaviour.

**Comment by TheAlgo** [comment]
[IMO]:  Also if we have a submodule in future this can also serve as an index , since everyone can make a PR to create a new tool or facility for deploying OpenSearch stack starting from here.

**Review by peterzhuamazon — APPROVED** [review]

**Pull request merged**
