### PR TITLE
Updating readme

### PR DESCRIPTION
**Pull request by amulyas**
### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by TheAlgo** [comment]
Nit : There is a typo in the Description hint

**Review by amulyas — COMMENTED** [review]
Helm is not working for me once its working I can add more details on readme

**Comment by TheAlgo** [comment]
Can you try checking out  #4 ? I have updated the chart

**Comment by peterzhuamazon** [comment]
Hi @amulyas we have merged #4 could you check again and update the PR?
The current setup can follow the ODFE docs:
https://opendistro.github.io/for-elasticsearch-docs/docs/install/helm/

**Comment by peterzhuamazon** [comment]
Hi @amulyas it has been 7 days since we last chat.
Would close this PR for now please feel free to reopen it at any time.

Thanks.

**Pull request closed without merging**
