### PR TITLE
Reset chart version back to 0.1.0

### PR DESCRIPTION
**Pull request by smlx**
### Description
The chart is still experimental, and not a stable release yet. And it hasn't been published.

I assume this will be required before #12, but if you do intend to have this chart as 1.0.0 then please just go ahead and close the PR :slightly_smiling_face: 
 
### Issues Resolved
n/a
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by TheAlgo — APPROVED** [review]
I kind of agree with this change. We can follow the versioning as per the Helm Universe.

**Comment by DandyDeveloper** [comment]
Not sure I understand the reason for this? Seems redundant, experimental should be indicated on the README / Chart file. I don't think versioning matters.

**Comment by smlx** [comment]
The only reason for this is to indicate to users the state of the chart. SemVer breaking changes require a major version bump past 1.0.0, and given comments like https://github.com/opensearch-project/opensearch-devops/pull/4#issuecomment-884700531 it seems that the `values.yaml` interface is not yet stable, so you might end up at version 20.0.0 quite quickly.

If that doesn't matter please close this :slightly_smiling_face:

**Comment by peterzhuamazon** [comment]
I am ok to keep AppVersion 1.0.0 while Chart Version 0.1.0, as I do see the benefits described by @smlx.
It is just a habit back in ODFE we sync them both:
https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/main/helm/opendistro-es/Chart.yaml

**Comment by peterzhuamazon** [comment]
Will close this PR if no more support in a few days.

**Pull request closed without merging**
